### PR TITLE
Use fixed protobuf version and grpcio version to avoid importing bugs.

### PR DESCRIPTION
**Pull request by typhoonzero**
`import sqlflow` will cause error `AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'` in the sqlflow:dev Docker image since the protobuf version is `3.7.1` which does not work with `grpcio-tools==1.32.0`

Related https://github.com/sql-machine-learning/sqlflow/issues/890, I'm adding `ipython.sh` to CI.

### CODE REVIEW

**Review by lhw362950217 — APPROVED** [review]
LGTM
